#+TITLE: Problem Set 1 - Introduction to Julia
#+AUTHOR: Gabriel Petrini, Prof. Tyler Ransom
#+DATE: September 1st 2020, 9:00 AM
#+PROPERTY: header-args: :results output :exports both :async t
#+PROPERTY: header-args:julia :tangle gps_PS1.jl
#+PROPERTY: header-args:julia :session *julia*

#+BEGIN_SRC elisp :exports none :results silent
(setq org-list-allow-alphabetical t)
#+END_SRC

* Directions

Directions: Answer all questions. Each student must turn in their own copy, but you may work in groups. Clearly label all answers. Show all of your code. Turn in jl-file(s), output files and writeup via GitHub. Your writeup may simply consist of comments in jl-file(s). If applicable, put the names of all group members at the top of your writeup or jl-file.

#+BEGIN_SRC juliausing Random, Distributions, FreqTables, Statistics
using LinearAlgebra
using JLD2, CSV, DataFrames

Random.seed!(1234)
#+END_SRC

#+RESULTS:



* Initializing variables and practice with basic matrix operations

a) Create the following four matrices of random numbers, \emph{setting the seed to} `1234'. Name the matrices and set the dimensions as noted
   1. $A_{10\times7}$ - random numbers distributed $U\left[-5,10\right]$

#+BEGIN_SRC julia
A = rand(Uniform(-5,10), 10,7)
#+END_SRC

#+RESULTS:


   3. $B_{10\times7}$ - random numbers distributed $N\left(-2,15\right)$ [st dev is $15$]
   4. $C_{5\times7}$ - the first 5 rows and first 5 columns of $A$ and the last two columns and first 5 rows of $B$
   5. $D_{10\times7}$ - where $D_{i,j}=A_{i,j}$ if $A_{i,j}\leq0$, or $0$ otherwise

